openapi: 3.0.3
info:
  title: Anonymised Candidate Data API
  description: Talent Catalog API specification for accessing anonymised candidate data.
  version: 1.0.0
  termsOfService: https://tctalent.org/terms
  contact:
    name: Talent Catalog API Support
    url: https://github.com/Talent-Catalog/tc-anonymization-service-spec/issues
    email: support@talentcatalog.net
  license:
    name: Gnu Affero General Public License
    url: https://www.gnu.org/licenses/agpl-3.0.html
  x-logo:
    url: ./assets/tc-logo.png
    altText: Talent Catalog logo

tags:
  - name: Candidates
    description: Operations related to anonymised candidates

servers:
  - url: https://tctalent.org/ads
    description: Production server
  - url: https://tctalent-test.org/ads
    description: Staging server

paths:
  /v1/candidates:
    $ref: paths/v1/candidates.yaml
  /v1/candidates/{candidateId}:
    $ref: ./paths/v1/candidates-candidateId.yaml
  /v1/candidates/byListId/{listId}:
    $ref: ./paths/v1/candidates-byListId-listId.yaml
  /v1/candidates/bySearchId/{searchId}:
    $ref: ./paths/v1/candidates-bySearchId-searchId.yaml

components:
    schemas:
      IdentifiableCandidate:
        $ref: ./components/schemas/v1/IdentifiableCandidate.yaml

